### ISSUE TITLE
Gather HCA statistics

### ISSUE THREAD

**Issue by guilbaults** [guilbaults/infiniband-exporter#25]
At the moment, only the statistics of the switches are collected. The original idea was to limit interaction with the compute nodes since every packets go to a switch, so the switch counters see all the traffic. This implementation does not capture errors that are localized on the HCA of a compute node, only the errors on the switches are seen. 

`ibqueryerrors` is currently called with `--switch`, it should run without that flag, or run twice with the `--ca` flag on the second execution.

**Comment by gabrieleiannetti** [comment]
Hi,

I think it is more efficient to run `ibqueryerrors` just one time with `--switch` and `--ca` flags set.  
And also might take less time, as we will see below...

As I can tell by now, with the errors `src/query_smp.c:195; umad (DR path slid 0; dlid 0; 0,1,13,5,14 Attr 0x11:0) bad status 110; Connection timed out` showing up from `ibqueryerrors` a run of ibqueryerrors took about ~25 seconds. But now as the problem has been solved, the error messages do not show up anymore and a run does take about ~1-3 seconds.

Here a picture with the exporter scrape durations:  

![infiniband_scrape_duration_seconds](https://user-images.githubusercontent.com/20843186/115370404-531f7100-a1c9-11eb-8f55-a72520597531.png)

**Comment by gabrieleiannetti** [comment]
Hi, 

I would prefer to just run `ibqueryerrors` one time with `--switch` and `--ca` flag enabled.  

Looks like a more clear approach to me.  

For instance
* errors on STDERR are not duplicated
* timeouts are not doubled retrieved on errors with `bad status 110; Connection timed out`
* process one input source, this is also beneficial for processing an input file

**Comment by guilbaults** [comment]
Thanks, merged
