### ISSUE TITLE
Missing counter names

### ISSUE THREAD

**Issue by mrobbert** [guilbaults/infiniband-exporter#46]
I just started using this exporter recently and found a total of three counters that showed up as missing in my error output while running it on my two clusters. The names are:

PortXmitConstraintErrors
PortMalformedPktErrors
PortSwLifetimeLimitDiscards

I was able to get rid of the errors by adding those to self.counter_info locally. I'd like it if they could be added to the upstream code.

Thanks!

**Comment by gabrieleiannetti** [comment]
Hi,  
you could create an PullRequest (PR) similar to this one:  
https://github.com/guilbaults/infiniband-exporter/pull/45

E.g.  
* incrementing the micro version of the exporter
* adding missing counter
* updating the readme for the new counter

Best
Gabriele

**Comment by mrobbert** [comment]
Created pull request #47

**Comment by guilbaults** [comment]
Thanks for the merge request !
