### ISSUE TITLE
Add exporter scrape duration and ok metric

### ISSUE THREAD

**Issue by gabrieleiannetti** [guilbaults/infiniband-exporter#8]
Hi,

it would be very useful, to have the following metrics also exported:  

* scrape_duration_seconds
* scrape_ok

What do you think?

**Comment by guilbaults** [comment]
Hi, is this merge request OK for your use case ?

https://github.com/guilbaults/infiniband-exporter/pull/9

**Comment by guilbaults** [comment]
Changes done in https://github.com/guilbaults/infiniband-exporter/commit/c6eef51246a91ccf81f2364c45ca7dfc9d266fc7
